/** Textes des pages /creer-ma-roue et /rendez-vous (formulaires). */
import { EMAIL } from "@/config";

export const consentText = `J'accepte que Rouelia utilise ces informations pour répondre à ma demande et me recontacter à ce sujet. Je peux retirer mon accord à tout moment en écrivant à ${EMAIL}.`;

export const createWheel = {
  path: "/creer-ma-roue",
  title: "Créer ma roue à cadeaux",
  description:
    "Créez votre roue à cadeaux Rouelia vous-même en 5 minutes, ou envoyez-nous vos infos : on la prépare pour vous et votre QR code arrive sous 24 à 48 h.",
  eyebrow: "Créer ma roue",
  h1: "Votre roue, prête aujourd'hui.",
  lead: "Deux façons de démarrer, toutes les deux avec 14 jours d'essai gratuit et sans carte bancaire.",
  choose: "Choisissez votre parcours",
  paths: {
    moi: {
      id: "moi-meme",
      title: "Je crée ma roue moi-même",
      text: "Vos lots, vos couleurs, votre logo. Vous testez la roue comme un client, en direct.",
      badge: "5 minutes",
    },
    pourMoi: {
      id: "pour-moi",
      title: "Créez-la pour moi",
      text: "Vous nous donnez l'essentiel, on s'occupe du reste. QR code par e-mail sous 24 à 48 h.",
      badge: "Le plus simple",
    },
  },
  demoTitle: "Réglez votre roue. Tournez-la comme un client.",
  form: {
    title: "Dites-nous l'essentiel",
    lead: "Une seule étape. On prépare votre roue et on vous envoie votre QR code.",
    shopName: "Nom du commerce",
    name: "Votre prénom",
    nameHelp: "Facultatif, pour savoir comment vous appeler.",
    logo: "Logo",
    logoHelp: "Facultatif. JPG, PNG ou SVG, 5 Mo au plus.",
    logoChoose: "Choisir une image",
    logoReplace: "Changer",
    logoRemove: "Retirer",
    phone: "Téléphone",
    email: "E-mail",
    address: "Adresse du commerce",
    google: "Lien de votre fiche Google, ou nom de l'établissement",
    googleHelp: "Le nom suffit si vous n'avez pas le lien sous la main.",
    prizes: "Lots souhaités",
    prizesHelp: "Facultatif. Par exemple : café offert, dessert offert, -10 % sur la prochaine visite. Sinon, on vous propose une sélection adaptée à votre métier.",
    message: "Message",
    messageHelp: "Facultatif. Horaires, couleurs, une idée particulière...",
    submit: "Envoyer ma demande",
    next: "vous recevez un e-mail de confirmation. Nous préparons votre roue et vous envoyons votre QR code par e-mail sous 24 à 48 h.",
    submitting: "Envoi en cours",
    errors: {
      shopName: "Indiquez le nom de votre commerce.",
      phone: "Ce numéro ne ressemble pas à un numéro français. Exemple : 06 12 34 56 78.",
      email: "Cet e-mail semble incomplet. Vérifiez le @ et le point.",
      address: "Indiquez l'adresse du commerce.",
      google: "Indiquez le lien de votre fiche Google ou le nom de l'établissement.",
      consent: "Cochez la case pour qu'on puisse traiter votre demande.",
      logoType: "Ce fichier n'est pas une image. Essayez un JPG, un PNG ou un SVG.",
      logoSize: "Cette image dépasse 5 Mo. Essayez une version plus légère.",
      summary: "Il manque quelques informations, elles sont indiquées en rouge.",
      server: "L'envoi n'a pas fonctionné. Réessayez, ou écrivez-nous sur WhatsApp.",
      rate: "Trop de demandes depuis cette connexion. Réessayez dans un moment.",
    },
    success: {
      title: "C'est parti.",
      text: "Vous recevrez votre QR code par e-mail sous 24 à 48 h.",
      note: "Un e-mail de confirmation vient de partir. Pensez à regarder vos courriers indésirables.",
    },
  },
};

export const booking = {
  path: "/rendez-vous",
  title: "Réserver un appel gratuit de 5 minutes",
  description:
    "Réservez un appel gratuit de 5 minutes avec Rouelia : choisissez un créneau, on vous appelle pour répondre à vos questions sur la roue à cadeaux.",
  eyebrow: "Appel gratuit",
  h1: "Un appel de 5 minutes, au moment qui vous arrange.",
  lead: "Choisissez un créneau, on vous appelle. Pas de démonstration interminable : vos questions, nos réponses, sans engagement.",
  points: ["Gratuit et sans engagement", "On vous appelle, vous n'avez rien à préparer", "Heure de Paris"],
  calendarTitle: "Choisissez un jour",
  slotsTitle: (day: string) => `Créneaux du ${day}`,
  noSlot: "Plus aucun créneau ce jour-là. Essayez un autre jour.",
  closed: "Fermé",
  loading: "Chargement des créneaux",
  loadError: "Les créneaux n'ont pas pu être chargés. Réessayez, ou écrivez-nous sur WhatsApp.",
  retry: "Réessayer",
  slotLabel: (when: string) => `Créneau choisi : ${when}`,
  change: "Changer de créneau",
  form: {
    title: "Vos coordonnées",
    name: "Nom",
    phone: "Téléphone",
    email: "E-mail",
    emailHelp: "Pour recevoir la confirmation et l'invitation pour votre agenda.",
    shop: "Commerce",
    shopHelp: "Facultatif.",
    submit: "Réserver ce créneau",
    next: "vous recevez tout de suite un e-mail de confirmation avec l'invitation pour votre agenda. Nous vous appelons au créneau choisi, au numéro indiqué.",
    submitting: "Réservation en cours",
    errors: {
      name: "Indiquez votre nom.",
      phone: "Ce numéro ne ressemble pas à un numéro français. Exemple : 06 12 34 56 78.",
      email: "Cet e-mail semble incomplet. Vérifiez le @ et le point.",
      slot: "Choisissez un créneau.",
      consent: "Cochez la case pour qu'on puisse vous appeler.",
      taken: "Ce créneau vient d'être réservé. Choisissez-en un autre.",
      closed: "Ce créneau n'est plus disponible. Choisissez-en un autre.",
      server: "La réservation n'a pas fonctionné. Réessayez, ou écrivez-nous sur WhatsApp.",
      rate: "Trop de réservations depuis cette connexion. Réessayez dans un moment.",
    },
  },
  success: {
    title: "C'est réservé.",
    text: (when: string) => `On vous appelle ${when}, heure de Paris.`,
    note: "La confirmation et l'invitation pour votre agenda sont parties par e-mail.",
  },
  alternative: "Vous préférez écrire ?",
};
